### ISSUE TITLE
Automated wot install detection for diagnostic tools

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#129]
# **Is your feature request related to a problem? Please describe.**
When taking diagnostic zips, the app always asks for the game location. Yet the app can clearly detect game installs.

# **Describe the feature you'd like**
Instead of asking the user to locate the game install location, which they may not know, give the user every registry install of the game. If there is only one, then that is the default. The default for multiple would be the last used install, if exists

# **Describe alternatives you've considered**
N/A

# **Additional context**
The feature could be a button that opens another window, populated with all these installs (if multiple), or a dropdown (I know , "eww comboboxes"). The button could also be greyed out when there is only one install.

In the interest of ensuring the users ability to quickly fix an issue with this feature, there should still be a button to manually select an install. This button should have in brackets "(Advanced)". This would deter any new user from using it over the automated feature.

**Comment by Willster419** [comment]
this is related to discussions started by @SigmaTel71 

i want to change how the diagnostic tools handles wot detection while at the same time changing how the application handles detection

**Comment by Arkhorse** [comment]
oh, while your there, could you redesign the window? Currently it honestly looks like a hot mess. DIfferent sized buttons for one :P. The window should show the current selected wot path, maybe at the bottom.

**Comment by Arkhorse** [comment]
Id do the visual design myself, but my repo is setup for making the caveman language...

**Comment by Willster419** [comment]
This was partially done back with the complete re-work of how windows were handled (https://github.com/Willster419/RelhaxModpack/tree/1.3.0.0), but did not cover when the diagnostic tool was loaded for the first time without a wot client being selected from a previous install.

With (https://github.com/Willster419/RelhaxModpack/commit/c294a2a102594fef332a636a13bb1772a09775e5), the behavior was changed so that if it's empty, it will auto-select one. Additionally, when selecting a client location from the window, it will now present a custom new window that shows all detected clients and can allow the user to select one, or manually select one.

**Comment by Willster419** [comment]
added in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
