### ISSUE TITLE
Add a deprecated field to enable discussion of questionably old mods

### ISSUE THREAD

**Issue by Willster419** [Willster419/RelhaxModpack#131]
With a modpack this big, sometimes old packages or packages without info can look suspiciously out of date. While we don't want to keep old and especially not working packages in the database, there may be info about it that we simply do not have available at the time. I would like to implement the following idea:

A field, `deprecated`, that **anyone can set on a package**. Setting it implies one or more of the following:
- "This package no longer has a valid location to look for updates"
- "This package is no longer supported by the developer."
- "This package looks very out of date, does it even work? Does someone on the team maintain it?"

The idea is that during team meetings, we can discuss packages with these flags, and then as a team make a decision about what to do with the package. I think this can solve a lot of conflicts as to "what to do" with a package.

@Arkhorse @elektrosmoker @123Gauss @dirty20067 i'd like your opinion on this idea. I think it's good and should be used. Do you all think you would use it?

Maybe call it "needs attention" instead of deprecated?

**Comment by elektrosmoker** [comment]
erm...i want it!

**Comment by Arkhorse** [comment]
It would definitely prevent removing mods that are still maintained, but have no info posted for the team to use. 

This can also have an automated part of it: If a mod goes unchanged (packageZipFile) for say 3 months, the flag is auto applied (maybe with a check to ignore the package (like for patches for aux or PMOD)). 

If we get full git integration, maybe when someone flags the package, and pushes it, the commit would include a ping of the maintainer (would need to either use only git usernames here, or have some way to define who is who). This may require that field to be "required", rather than optional (again, automatic if we get git integration). 

This type of system would for me fall into the "nice to have, but not 100% needed" category. A simple check box would be very easy to implement, but wouldnt be what it can be.

**Comment by Arkhorse** [comment]
For now, we could just add a tag just to have it.

**Comment by Willster419** [comment]
added in release https://github.com/Willster419/RelhaxModpack/releases/tag/1.3.1.0
