### ISSUE TITLE
New method for handling patches

### ISSUE THREAD

**Issue by Arkhorse** [Willster419/RelhaxModpack#135]
Currently our patches are all in zips, within the `_patch` folder. This means we dont have a good source control for them. So, this idea will change that, and give us a more fine tuned control over source control of all patches.

## Design

So, this new system would be part of the `Editor`. Would be a seperate tab on the right. It would merge the `Patch Designer` into the editor, meaning both the Editor and the Patch Designer would be one program. 

The window would consist of the same buttons present in the current patch designer, except the save and load buttons.

### The patch data could be saved in at least two ways:
- [ ] As a new node within the Package node
- [ ] As a separate file, named with a new naming scheme (`<patchGroup>_<packageName>_<gameVersion>_<dateUTC>`.xml). The file would be saved in a new folder on our git database, perhaps simply named `RelhaxDownloads\Patches\`.

Using a seperate file would prevent the need to rewrite how patches are loaded, only change the target directory. It would also prevent file size bloat due to the patch data, and reduce download times.

### Pro's
- [ ] We would have proper source control over all patches
- [ ] We would no longer need to download an entire mod just to update a patch, that would normally be a few kb's
- [ ] Both the patcher and the editor would be one window, meaning less programs open

### Con's
- [ ] Both windows are now one, meaning you cant have them side by side. Not sure if this would actually affect anyone though
- [ ] More coding work for the application team
- [ ] Increased file downloads from the github repo

## Converting

So, with any new system, would would need to adapt ALOT of patches to the new system. If they are saved as a new file, rather than a node, that adaptation wouldnt take alot of time (could be automated either way). 

Good idea, yes?

**Comment by Willster419** [comment]
This was combined into a major re-write of the xml load/save system that allows separation of the loading/saving of the physical text and files and loading of the root database file(s), from the actual handling/mapping of xml components to internal modpack class properties. It additionally included a major re-structure of the class components related to database components so that it was much easier to load/save to/from xml.

The end result is that the editing of patches, shortcuts, xml unpacks (soon to be a copy step?) and atlas creations became the editing of (installation) *instructions*, and is now all able to be saved into the database using a new xml save format (called internally as 'schema' that is much more compact then the original format. The original format is still supported (kind of) in case other modpack developers wish to use raw files for patch instructions. (see https://github.com/Willster419/RelhaxModpack/issues/167)

This also means that there's less manipulation of zip files during extraction (parsing filenames for instructions), and there's no having to load instructions from disk since they are loaded already in the database and is only internal list manipulation.

Big thanks for the idea(s), this is finally a reality. (See https://github.com/Willster419/RelhaxModpack/pull/166 to track the PR)

**Comment by Willster419** [comment]
see pr https://github.com/Willster419/RelhaxModpack/pull/168
