### ISSUE TITLE
Update application manifest to detect Windows versions correctly

### ISSUE THREAD

**Issue by SigmaTel71** [Willster419/RelhaxModpack#153]
# **Is your feature request related to a problem? Please describe.**
It's more a problem rather than a feature request. 

# **Describe the feature you'd like**
Update the application manifest to detect Windows 8.1/Windows 10/newer versions [correctly](https://docs.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1).

# **Additional context**
Is that caused by using deprecated functions to get OS version?..
I'm running Windows 8.1, but Relhax falsely detects that it's Windows 8. Windows 10 will respond the same way because the manifest is... blank. Literally.
![image](https://user-images.githubusercontent.com/17989678/123288643-70015900-d518-11eb-829c-f73161fc4d12.png)

**Comment by Willster419** [comment]
Yup, turns out i was running without a manifest. Looked into it here:
https://www.prugg.at/2019/09/09/properly-detect-windows-version-in-c-net-even-windows-10/
and it was easy as adding a manifest and listing the versions of supported windows . 

https://github.com/Willster419/RelhaxModpackDatabase/commit/68cf3fa36d09c3433ddebd62d279d3a15d303327

![image](https://user-images.githubusercontent.com/2482828/123328666-b773ef00-d4f0-11eb-9cc2-2acb138295ee.png)


nice find, thanks!

**Comment by Willster419** [comment]
note: we currently only have windows dependent code for windows 7, so this was never found

**Comment by SigmaTel71** [comment]
That's okay, I remember you said that you will never drop Windows 7 support, even if WG will. Or was it someone else? :thinking:

**Comment by Willster419** [comment]
I don't plan on dropping windows 7 support for several years. My laptop won't update to the newest windows 10 and is out of support anyways, and i don't want the new windows 11. I'll probably be installing windows 7 or 8.1 soon anyways with a windows 10 and 11 vm for testing in those environments

**Comment by SigmaTel71** [comment]
Updated the app, now I'm really happy to see proper lines in the log file. I guess I can close the issue. :smile: 
![image](https://user-images.githubusercontent.com/17989678/123467779-8e8b5100-d5f9-11eb-8716-2fab7bd4550c.png)
