### ISSUE TITLE
man1aq will cause tank info panel disabled

### ISSUE THREAD

**Issue by Goolloo** [Willster419/RelhaxModpack#8]
installing man1aq icon set, both regular and premium version will disable the tank info panel.

**Comment by Willster419** [comment]
thank you for taking the time to identify what the problem is and which mod is causing it. this saves me lots of time when updating the database :)
the root of the cause has been identified to a tank contour icon maker program that is causing this issue.
until the contour mods are updated, they are disabled.
currently the only one updated is pogs

**Comment by Willster419** [comment]
xvm was updated, as well as the panels. Is this still an issue?
